### ISSUE TITLE
Alternative conditioning mechanism?

### ISSUE THREAD

**Issue by metatl** [apapiu/transformer_latent_diffusion#16]
Great lean transformer LDM! 

I'm wondering if you can make the conditioning mechanism more versatile. For example, allowing conditioning on tensors that are encoded before entering a cross-attention layer in the diffusion backbone? I think this would make the code even useful for wider applications.

**Comment by apapiu** [comment]
Hi @metatl not sure I understand your question - you can condition on any tensor you want to here - https://github.com/apapiu/transformer_latent_diffusion/blob/2352f0051c40340bacd67920a56c7af91bfab93d/tld/transformer_blocks.py#L137 - is this what you would want?

**Comment by metatl** [comment]
I think you are right. I just need to encode the conditioning image into a tensor and pass it to the model.
